version: '3.7'


services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=iee#&-lxan(hp3lsg!7rq=gijtv%q#z^q+-81qhc+373f6*qfy
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51LjfEOH3XsXunZLDqELXeG8ocOLbH8iaRweJZlJl8pTk6PwWI0nIEvUuffmqsKpEdPw6asfCwJrfHiduFyOGPyDY00okkyiYMK
      - STRIPE_TEST_SECRET_KEY=sk_test_51LjfEOH3XsXunZLDHMeYSLiLgbGwrhnxlgCKFVhE4LVmVvFE4D3yHUFMdUhUNZDT3TyVMl7fHvoBKd577UlnNG8100NURC7cwQ
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: '123456789'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
volumes:
  postgres_data: